### ISSUE TITLE
Small issue in TPR.fit()

### ISSUE THREAD

**Issue by sparkqkr** [jerryfsu3333/TRES#1]
Hi, Thanks for your hard working to renew the package.

To get the coefficient in TPR.fit()
"TPR.fit(X,y,u=,method="PLS")$coefficients" doesn't work.
Instead of the statement, we need to get from "TPR.fit(X,y,u=,method="PLS")[[5]]" and "unlist()" it for using as vector.

**Comment by jingzzeng** [comment]
Thanks for the feedback. Could you please give your output of `TPR.fit(X,y,u=,method="PLS")$coefficients`? 

The outputs of `TPR.fit()` is supposed to be a Tensor class data, to retrieve the numerical data, use `@data`. Please try
`
fit <- TPR.fit(X,y,u,method="PLS")
`
`
coef(fit)@data   # Or coefficients(fit)@data
`
and see if it works.
